version: 2.1
orbs:
  aws-s3: circleci/aws-s3@2.0.0
  cfy-ci: cloudify/cfy@1.0.2
jobs:
  simple:
    executor: cfy-ci/default
    steps:
      - checkout
      - cfy-ci/create:
          environment-name: test-app-${CIRCLE_BUILD_NUM}
          blueprint: simple/blueprints/simple/blueprint.yaml
          outputs-file: simple-env-data.json
      - store_artifacts:
          path: simple-env-data.json
      - cfy-ci/delete:
          environment-name: test-app-${CIRCLE_BUILD_NUM}
  arm:
    executor: cfy-ci/default
    steps:
      - checkout
      - cfy-ci/arm:
          environment-name: arm-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
          resource-group: circlearmrg${CIRCLE_BUILD_NUM}
          location: centralus
          template-file: arm/environment.json
          parameters-file: arm/test-params/integration.yaml
          outputs-file: arm-env-data.json
      - store_artifacts:
          path: arm-env-data.json
      - cfy-ci/delete:
          environment-name: arm-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
  cloudformation:
    executor: cfy-ci/default
    steps:
      - checkout
      - cfy-ci/cfn:
          environment-name: cfn-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
          stack-name: circlecfnstack${CIRCLE_BUILD_NUM}
          template-file: cfn/stack.yaml
          parameters-file: cfn/test-params/integration.yaml
          outputs-file: cfn-env-data.json
      - store_artifacts:
          path: cfn-env-data.json
      - cfy-ci/delete:
          environment-name: cfn-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
  kubernetes:
    executor: cfy-ci/default
    steps:
      - checkout
      - cfy-ci/kubernetes:
          environment-name: k8s-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
          token: ${KUBERNETES_TOKEN}
          master-host: ${KUBERNETES_MASTER_HOST}
          namespace: default
          app-definition-file: k8s/app.yaml
          skip-ssl-verification: true
          outputs-file: k8s-env-data.json
      - store_artifacts:
          path: k8s-env-data.json
      - cfy-ci/delete:
          environment-name: k8s-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
  terraform:
    executor: cfy-ci/default
    steps:
      - checkout
      - run:
          name: Archive Terraform files
          command: |
            tar -cvzf /tmp/terraform-module.tar.gz -C tf/modules/ .
      - aws-s3/copy:
          from: /tmp/terraform-module.tar.gz
          to: 's3://cloudify-cicd-public/terraform-module.tar.gz'
      - cfy-ci/terraform:
          environment-name: tf-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
          module-file: https://cloudify-cicd-public.s3.amazonaws.com/terraform-module.tar.gz
          variables-file: tf/test-params/integration.yaml
          environment-mapping: AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY
          outputs-file: terraform-env-data.json
      - store_artifacts:
          path: terraform-env-data.json
      - cfy-ci/delete:
          environment-name: tf-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BUILD_NUM}
workflows:
  build:
    jobs:
      - simple
      - arm
      - cloudformation
      - kubernetes
      - terraform
